[package]
name = "sha2-derive-proc-macro"
authors = ["Mubelotix <mubelotix@gmail.com>"]
readme = "README-cratesio.md"
description = "The proc macro used by the sha2-derive crate."
license = "MIT"
version = "0.1.1"
edition = "2021"

[lib]
proc-macro = true
